repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
  - repo: https://github.com/open-policy-agent/conftest
    rev: v0.44.0
    hooks:
      - id: conftest
        name: OPA Rego Policy Check
        entry: conftest test policy/
        language: system
        types: [terraform]
