name: Zscaler OPA Unit Tests

on:
  push:
    paths:
      - "policy/test/**/*.yaml"
      - "policy/**/*.rego"

jobs:
  test_rego_policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.34.0/conftest_0.34.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.34.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Run Policy Unit Tests
        run: conftest test --policy policy/ policy/test/
